### ISSUE TITLE
Query a specific table in an HTML document

### ISSUE THREAD

**Issue by NicolaZordan** [usesql/roadmap#12]
I would like to be able to get data from different parts of a web page
specifying id or name

for example:
1. which table: being able to specify what table to get data from, if the page contains multiple table
2. lists: being able to get data from lists in a web page ul, or ol
3. select: be able to get data from a select input, sometime used for menus 

examples:

- which table
http://website.com/page.html#table1
http://website.com/page.html#table2

- lists
http://website.com/page.html#listName1
http://website.com/page.html#listName2

- select
http://website.com/page.html@formName.fieldName

**Comment by dylanroy** [comment]
Added this capability. Here is a quick tutorial on the usage:
https://app.gitbook.com/@dylanroy/s/usesql/tutorials/retrieving-data-from-a-specific-table-in-a-web-page

**Comment by dylanroy** [comment]
I will be creating two additional tickets for the lists, and select fields.
