### ISSUE TITLE
Query Caching

### ISSUE THREAD

**Issue by ezcell** [usesql/roadmap#15]
💡 For general support requests and bug reports, please email [support@usesql.com](mailto:support@usesql.com) or check [docs.usesql.com](https://docs.usesql.com)

**Is your feature request related to a problem? Please describe.**
No real problem as such, just would speed up workflows and reduce server fees, 

**Describe the solution you'd like**
Would be great to have the same sql query served from cache instead of run every time. Optional refresh time as well (ie 24 hours)

**Comment by dylanroy** [comment]
Going to explore this implementation through a concept of saved queries. A query will get a named uri, and will not be refreshed unless it's expired or ?refresh=true.

E.g. https://usesql.com?query=xxxxx will be saved with the name revenue-report, an expiration range will be set (e.g. 24 hours, one week, one month). This will be cached and won't be queried again until it expired. It will be called via a named endpoint such as https://usesql.com/query/userid/revenue-report

**Comment by dylanroy** [comment]
The saved query feature can be accessed here when logged in:
https://www.usesql.com/queries

A short description of the functionality can be found here:
https://docs.usesql.com/getting-started/saved-queries
