### ISSUE TITLE
Ability to 'name' API keys

### ISSUE THREAD

**Issue by ezcell** [usesql/roadmap#18]
💡 For general support requests and bug reports, please email [support@usesql.com](mailto:support@usesql.com) or check [docs.usesql.com](https://docs.usesql.com)

**Is your feature request related to a problem? Please describe.**
I'd love to be able to assign a name to an API key, not just the domain limitation - helps keep track of what is doing what.

**Describe the solution you'd like**
Another field on the "Add key" screen to add an (optional) name to that key

**Comment by dylanroy** [comment]
Agreed, I am starting to lose my demo keys due to not having this.

**Comment by dylanroy** [comment]
Added the ability to label add or update a label to one's keys.

**Comment by dylanroy** [comment]
Just click on the bottom right of your key tile on the button that says "Label" to apply one.
