### ISSUE TITLE
Ability to query private Google Sheets

### ISSUE THREAD

**Issue by dylanroy** [usesql/roadmap#7]
💡 For general support requests and bug reports, please email [support@usesql.com](mailto:support@usesql.com) or check [docs.usesql.com](https://docs.usesql.com)

**Is your feature request related to a problem? Please describe.**
Currently only publicly available resources can be accessed via the API. If this is a feature you need please upvote this.

**Comment by ezcell** [comment]
This is huge, would be much easier on my nerves if my gsheets arnt shared publicly,

**Comment by dylanroy** [comment]
This is now possible. Please see the documentation below to implement:
https://docs.usesql.com/tutorials/integrate-with-a-private-google-sheet
